### ISSUE TITLE
Empty WiFi Name

### ISSUE THREAD

**Issue by mac-user-89271** [vborodulin/wifi-loc-control#1]
I've run rich logs, and it looks like the `wifi_name` function isn't working as expected:

```
[2024-03-08 15:28:03] current wifi_name ''
[2024-03-08 15:28:03] wifi_name is empty
```
Any ideas on how to fix this?

**Comment by vborodulin** [comment]
hello, can you share some extran info like wifi list screenshot and you network location settings

**Comment by nonsavant** [comment]
Also having this problem, Mac OS 14.4.1

Suspect that this is the problem:

```
% /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I               
WARNING: The airport command line tool is deprecated and will be removed in a future release.
For diagnosing Wi-Fi related issues, use the Wireless Diagnostics app or wdutil command line tool.
```

the airport command line tool is being used at https://github.com/vborodulin/wifi-loc-control/blob/af31d25fbe9b710d505e6365b029dfb1f5c6d653/wifi-loc-control.sh#L22C13-L22C153

**Comment by nonsavant** [comment]
`sudo wdutil info | grep '\sSSID' | sed -nE 's/[[:space:]]*SSID.*:[[:space:]]*(.*)/\1/p')`

could potentially replace that line, but I think that the `sudo` may cause problems?

**Comment by ollisulopuisto** [comment]
It should be fixed by using 

`wifi_name="$(networksetup -getairportnetwork en0 | awk -F ': ' '{print $2}')"`

**Comment by vborodulin** [comment]
fixed in https://github.com/vborodulin/wifi-loc-control/pull/2

**Comment by afonsofrancof** [comment]
@vborodulin .
This is failing for me on MacOS Sequoia.
When querying the name I get the following

```
❯ networksetup -getairportnetwork en0
You are not associated with an AirPort network.
```

The command @nonsavant proposed works (I needed to fix it by removing the last bracket)

`sudo wdutil info | grep '\sSSID' | sed -nE 's/[[:space:]]*SSID.*:[[:space:]]*(.*)/\1/p'`

But I don't know if we can use `sudo`

**Comment by samgurung** [comment]
i replace the wdutil line with this and it worked
`wifi_name=$(system_profiler SPAirPortDataType | awk '/Current Network/ {getline;$1=$1;print $0 | "tr -d ':'";exit}')`

**Comment by vborodulin** [comment]
great! i'll check this in a week
