### ISSUE TITLE
Broken in Sequoia

### ISSUE THREAD

**Issue by pimvandenbroek** [vborodulin/wifi-loc-control#5]
Hi,

The wifi-loc-control.sh script is broken, as `networksetup -getairportnetwork en0` returns empty on Sequoia [stackexchange](https://apple.stackexchange.com/questions/475370/networksetup-getairportnetwork-return-you-are-not-associated-with-an-airport-ne)

Not sure if there is a solution for this yet, but changing the script from:
`wifi_name="$(networksetup -getairportnetwork en0 | awk -F ': ' '{print $2}')"`
to 
`wifi_name="$(ipconfig getsummary en0 | awk -F ' SSID : '  '/ SSID : / {print $2}')"`
fixed it

**Comment by vborodulin** [comment]
can you make pls pull request to merge it
